name: Terraform CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/branch

permissions:
  contents: read
  pull-requests: write

jobs:

  terraform-ci:
    defaults:
      run:
        working-directory: environment/Preprod

    name: Terraform CI
    runs-on: ubuntu-latest

    steps:

      # -------------------------
      # Checkout Code
      # -------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4


      # -------------------------
      # Setup Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8


      # -------------------------
      # Terraform Format
      # -------------------------
      - name: Terraform Format Check
        run: terraform fmt -check -recursive


      # -------------------------
      # Terraform Init
      # -------------------------
      - name: Terraform Init
        run: terraform init -input=false


      # -------------------------
      # Terraform Validate
      # -------------------------
      - name: Terraform Validate
        run: terraform validate


      # -------------------------
      # TFLint
      # -------------------------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          tflint --init
          tflint


      # -------------------------
      # Terraform Security Scan
      # -------------------------
      - name: Run TFSEC
        uses: aquasecurity/tfsec-action@v1.0.3


      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        run:
          az login\
            --service-principal \
            --username "493a4772-8f8e-4e30-af6d-d10b5e9820d7" \
            --password "KSW8Q~6m2NXBltaSNLpUYpa6KGbUoijvhsbilbMl" \
            --tenant "45079bb7-e7a0-49e5-bac0-8a65f3b2946c"

      - name: Verify Azure Login
        run: |
          az account show
          az group list --output table

      # -------------------------
      # Terraform Plan
      # -------------------------
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan


      # -------------------------
      # Upload Plan
      # -------------------------
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: environment/Preprod/tfplan